language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
before_script:
  - "./bin/consul agent --server=true --bootstrap-expect=1 --data-dir=."
script: ansible-playbook -i ./hosts test-consul.yml
