---

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  sudo: False
  vars_files:
    - group_vars/consul

  tasks:

    - name: PUT value for key
      consul_kv: action=put key=foo value=bar

    - name: PUT value for nested key
      consul_kv: action=put key=bar/baz/foo value="{\"name\":\"inglebert\"}"

    - name: PUT value with flag
      consul_kv: action=put key=bar/baz/bizzle value="shizzle" flags=23

    - name: GET value
      consul_kv: action=get key=foo
      register: foo_key

    - name: Debug gotten value
      debug: var=foo_key
      when: foo_key is defined

    - name: Debug values
      debug: var=foo_key.value

    - name: GET keys for prefix
      consul_kv: action=get key=bar keys=true
      register: bar_keys

    - name: Debug keys for prefix
      debug: var=bar_keys
      when: bar_keys is defined

    - name: GET keys up to separator
      consul_kv: action=get key=bar/ keys=true separator='/'
      register: separator_keys

    - name: Debug keys up to separator
      debug: var=separator_keys
      when: separator_keys is defined

    - name: PUT key without value
      consul_kv: action=put key=foo
      ignore_errors: true

    - name: PUT value for recursive DELETE
      consul_kv: action=put key=dir/to/remove/recursively value="shizzle" flags=23

    - name: Recursive DELETE of directory
      consul_kv: action=delete key=dir recurse=true

    - name: DELETE key
      consul_kv: action=delete key=foo

    - name: DELETE unknown key
      consul_kv: action=delete key=what/nope/maybe/nah

    - name: DELETE with invalid check and set
      consul_kv: action=delete key=bar/baz/foo cas=0

    - name: DELETE with valid check and set
      consul_kv: action=delete key=bar/baz/foo cas=100

    - name: PUT key into dc2
      consul_kv: action=put key=wat value="{\"some\":\"JSON\"}" dc="dc2" port=8510
