---

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  sudo: False
  vars_files:
    - group_vars/consul
  tasks:

    - name: Set value for key
      consul_kv: action=put key=foo value=bar
