---

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  sudo: False
  vars_files:
    - group_vars/consul

  tasks:

    - name: Session create
      consul_session: action=create ttl="15s"
      register: session
      tags:
        - session

    - name: Debug created session
      debug: var=session
      tags:
        - session

    - name: Session create with all params
      consul_session: action=create lock_delay="25s" ttl="25s"
      register: session_params
      tags:
        - session

    - name: Get session params info
      consul_session: action=info session={{session_params.value.ID}}
      register: session_params_info
      tags:
        - session

    - name: Debug session params
      debug: var=session_params_info
      tags:
        - session

    - name: Get session info
      consul_session: action=info session={{session.value.ID}}
      register: session_info
      tags:
        - session

    - name: Debug session info
      debug: var=session_info
      tags:
        - session

    - name: Get session renew
      consul_session: action=renew session={{session.value.ID}}
      register: session_renew
      tags:
        - session

    - name: Debug session renew
      debug: var=session_renew
      tags:
        - session

    - name: Destroy session
      consul_session: action=destroy session={{item}}
      with_items:
        - "{{session.value.ID}}"
        - "{{session_params.value.ID}}"
      tags:
        - session
