---

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  sudo: False
  vars_files:
    - group_vars/consul

  tasks:

    - name: Set value for key
      consul_kv: action=put key=foo value=bar

    - name: Set value for nested key
      consul_kv: action=put key=bar/baz/foo value="{\"name\":\"inglebert\"}"

    - name: Get value
      consul_kv: action=get key=foo
      register: foo_key

    - name: Debug gotten value
      debug: var=foo_key
      when: foo_key is defined

    - name: Get keys for prefix
      consul_kv: action=get key=bar keys=true
      register: bar_keys

    - name: Debug keys for prefix
      debug: var=bar_keys
      when: bar_keys is defined

    - name: Get keys up to separator
      consul_kv: action=get key=bar/ keys=true separator='/'
      register: separator_keys

    - name: Debug keys up to separator
      debug: var=separator_keys
      when: separator_keys is defined

    - name: Debug values
      debug: var=foo_key.value

    - name: Set key without value
      consul_kv: action=put key=foo
      ignore_errors: true

    - name: Recursive delete of directory
      consul_kv: action=delete key=bar recurse=true

    - name: Delete key
      consul_kv: action=delete key=foo

    - name: Delete unknown key
      consul_kv: action=delete key=what/nope/maybe/nah

    - name: Delete with invalid check and set
      consul_kv: action=delete key=bar/baz/foo cas=0

    - name: Delete with valid check and set
      consul_kv: action=delete key=bar/baz/foo cas=100

    - name: Put key into dc2
      consul_kv: action=put key=wat value="{\"some\":\"JSON\"}" dc="dc2" port=8510
